### ISSUE TITLE
Videos don’t show in every parent category

### ISSUE THREAD

**Issue by adam1000018** [arslancb/clipbucket#221]
When we add video to last child category it should be shown in every parent category.
For now it show up in parent categories but not in all.

Example: http://demo.clipbucket.com/alice-through-the-looking-glass-trailer-2-2016_v1741
This video is uploaded in category **Adult Comedies**
Hierarchy of categories for it looks like this:
Traillers / Latest / Comedy / Adult Comedies.
We can see this video only in:
**Adult Comedies**, **Comedy** (parent category for Adult Comedies), and **Latest** (parent category for Comedy).
We can’t see this video in **Traillers** (parent category for Latest and one of main categories).

**Comment by aliawancb** [comment]
This issue have been fixed in latest source.

**Comment by adam1000018** [comment]
This issue is still present.
Video shows only in 2 parent categorries up.
