### ISSUE TITLE
pagination next - Previous button issue cb 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#39]
pagination **next  -   Previous** button dose not work everywhere, channels page, search page and more..

**Comment by spirogg** [comment]
when viewing photos, you have to wait till the popup on the bottom right Quicklists) goes away before your mouse is allowed to click on any link on the page... ie. next or previous

really slow

PS: not logged in - as user on demo site v2.8.1

![clipbucket-photo-pagination-next-previous](https://cloud.githubusercontent.com/assets/17736688/15090200/7a7ebd24-13e3-11e6-9093-808c0f563325.JPG)

**Comment by sakydev** [comment]
Fixed!

**Comment by faral22** [comment]
Sorry but still does not work. also apply the fix, but still nothing. In the demo does not work
